site_name: Waffles
site_url: 'https://waffles.terrarum.net'
site_description: 'A simple configuration management system written in Bash'
site_dir: 'mkdocs-site'
repo_url: 'https://github.com/jtopjian/waffles'
theme: 'readthedocs'
google_analytics: ['UA-75603-16', 'waffles.terrarum.net']

markdown_extensions:
  - admonition

pages:
  - Home: 'index.md'
  - Installation: 'guides/install.md'
  - Concepts: 'concepts.md'
  - Usage: 'usage.md'
  - Modules: 'modules.md'
  - Functions:
    - 'Types': 'functions/types.md'
    - 'system': 'functions/system.md'
    - 'catalog': 'functions/catalog.md'
    - 'options': 'functions/options.md'
    - 'resource': 'functions/resource.md'
    - 'augeas': 'functions/augeas.md'
    - 'consul': 'functions/consul.md'
    - 'mysql': 'functions/mysql.md'
    - 'rabbitmq': 'functions/rabbitmq.md'
  - Guides:
    - 'Environment Variables': 'guides/environment-vars.md'
    - 'Deploying a MySQL Server': 'guides/deploying-a-mysql-server.md'
    - 'Deploying a MySQL Galera Cluster': 'guides/deploying-a-mysql-galera-cluster.md'
    - 'Deploying a Consul Cluster': 'guides/deploying-a-consul-cluster.md'
    - 'Overriding Data': 'guides/override-data.md'
    - 'Referencing Data from Data': 'guides/referencing-data-from-data.md'
    - 'Testing Waffles with Test Kitchen': 'guides/testing-with-test-kitchen.md'
    - 'Waffles and LXC': 'guides/waffles-and-lxc.md'
    - 'Waffles and Terraform': 'guides/waffles-and-terraform.md'
  - Resources:
    - Internals: 'resources.md'
    - stdlib.apt_key: 'resources/stdlib.apt_key.md'
    - stdlib.apt_ppa: 'resources/stdlib.apt_ppa.md'
    - stdlib.apt: 'resources/stdlib.apt.md'
    - stdlib.apt_source: 'resources/stdlib.apt_source.md'
    - stdlib.cron: 'resources/stdlib.cron.md'
    - stdlib.debconf: 'resources/stdlib.debconf.md'
    - stdlib.directory: 'resources/stdlib.directory.md'
    - stdlib.file_line: 'resources/stdlib.file_line.md'
    - stdlib.file: 'resources/stdlib.file.md'
    - stdlib.git: 'resources/stdlib.git.md'
    - stdlib.groupadd: 'resources/stdlib.groupadd.md'
    - stdlib.ini: 'resources/stdlib.ini.md'
    - stdlib.ip6tables_rule: 'resources/stdlib.ip6tables_rule.md'
    - stdlib.iptables_rule: 'resources/stdlib.iptables_rule.md'
    - stdlib.sudo_cmd: 'resources/stdlib.sudo_cmd.md'
    - stdlib.sysvinit: 'resources/stdlib.sysvinit.md'
    - stdlib.upstart: 'resources/stdlib.upstart.md'
    - stdlib.useradd: 'resources/stdlib.useradd.md'
    - apache.section: 'resources/apache.section.md'
    - apache.setting: 'resources/apache.setting.md'
    - augeas.aptconf: 'resources/augeas.aptconf.md'
    - augeas.cron: 'resources/augeas.cron.md'
    - augeas.file_line: 'resources/augeas.file_line.md'
    - augeas.generic: 'resources/augeas.generic.md'
    - augeas.host: 'resources/augeas.host.md'
    - augeas.ini: 'resources/augeas.ini.md'
    - augeas.json_array: 'resources/augeas.json_array.md'
    - augeas.json_dict: 'resources/augeas.json_dict.md'
    - augeas.mail_alias: 'resources/augeas.mail_alias.md'
    - augeas.shellvar: 'resources/augeas.shellvar.md'
    - augeas.ssh_authorized_key: 'resources/augeas.ssh_authorized_key.md'
    - consul.check: 'resources/consul.check.md'
    - consul.service: 'resources/consul.service.md'
    - consul.template: 'resources/consul.template.md'
    - consul.watch: 'resources/consul.watch.md'
    - keepalived.global_defs: 'resources/keepalived.global_defs.md'
    - keepalived.vrrp_instance: 'resources/keepalived.vrrp_instance.md'
    - keepalived.vrrp_script: 'resources/keepalived.vrrp_script.md'
    - keepalived.vrrp_sync_group: 'resources/keepalived.vrrp_sync_group.md'
    - mysql.database: 'resources/mysql.database.md'
    - mysql.grant: 'resources/mysql.grant.md'
    - mysql.user: 'resources/mysql.user.md'
    - nginx.events: 'resources/nginx.events.md'
    - nginx.global: 'resources/nginx.global.md'
    - nginx.http: 'resources/nginx.http.md'
    - nginx.if: 'resources/nginx.if.md'
    - nginx.location: 'resources/nginx.location.md'
    - nginx.map: 'resources/nginx.map.md'
    - nginx.server: 'resources/nginx.server.md'
    - nginx.upstream: 'resources/nginx.upstream.md'
    - python.pip: 'resources/python.pip.md'
    - python.virtualenv: 'resources/python.virtualenv.md'
    - rabbitmq.cluster_nodes: 'resources/rabbitmq.cluster_nodes.md'
    - rabbitmq.config_settings: 'resources/rabbitmq.config_settings.md'
    - rabbitmq.policy: 'resources/rabbitmq.policy.md'
    - rabbitmq.user_permissions: 'resources/rabbitmq.user_permissions.md'
    - rabbitmq.user: 'resources/rabbitmq.user.md'
    - rabbitmq.vhost: 'resources/rabbitmq.vhost.md'
